mysite/event_recorder/urls.py
from django.urls import path
from . import views

app_name = 'event_recorder'
urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),

  path('events/', views.EventIndexView.as_view(), 
        name='events-index'),
  path('events/<int:pk>/', views.EventDetailView.as_view(), 
        name='event-detail'),
  path('events/create/', views.EventCreateView.as_view(), 
        name='event-create'),
  path('events/<int:pk>/update/', views.EventUpdateView.as_view(), 
        name='event-update'),
  path('events/<int:pk>/delete/', views.EventDeleteView.as_view(), 
        name='event-delete'),

  path('categories/', views.CategoryIndexView.as_view(),
        name='categories-index'),
  path('categories/<int:pk>/', views.CategoryDetailView.as_view(), 
        name='category-detail'),
  path('categories/create/', views.CategoryCreateView.as_view(), 
        name='category-create'),
  path('categories/<int:pk>/update/', views.CategoryUpdateView.as_view(), 
        name='category-update'),
  path('categories/<int:pk>/delete/', views.CategoryDeleteView.as_view(), 
        name='category-delete'),

  path('people/', views.PersonIndexView.as_view(),
        name='people-index'),
  path('people/<int:pk>/', views.PersonDetailView.as_view(), 
        name='person-detail'),
  path('people/create/', views.PersonCreateView.as_view(), 
        name='person-create'),
  path('people/<int:pk>/update/', views.PersonUpdateView.as_view(), 
        name='person-update'),
  path('people/<int:pk>/delete/', views.PersonDeleteView.as_view(), 
        name='person-delete'),

  path('relations/', views.RelationIndexView.as_view(),
        name='relations-index'),
  path('relations/<int:pk>/', views.RelationDetailView.as_view(), 
        name='relation-detail'),
  path('relations/create/', views.RelationCreateView.as_view(), 
        name='relation-create'),
  path('relations/<int:pk>/update/', views.RelationUpdateView.as_view(), 
        name='relation-update'),
  path('relations/<int:pk>/delete/', views.RelationDeleteView.as_view(), 
        name='relation-delete'),

  path('ratings/', views.RatingIndexView.as_view(),
        name='ratings-index'),
  path('ratings/<int:pk>/', views.RatingDetailView.as_view(), 
        name='ratings-detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event_recorder.urls')),

]

mysite/event_recorder/models.py
import datetime
from enum import Enum

from django.db import models
from django.dispatch.dispatcher import receiver
from django.utils import timezone
from django.urls import reverse
#from django.db.models.signals import post_delete

 
# Create your models here.
'''
Category([ID], name, parent)
Relation([ID], name)
Person([ID], first_name, last_name, relations, approx_DOB, gender)
Event([ID], start_time, end_time, description, categories, people)
Value([ID], event, enjoyment, productivity)
'''

class Category(models.Model): 
  '''
  Basic event category names, as well as parent category
  if applicable. Each category can only have one parent supercategory.
  (Having both parent and child attributes leads to information
  redundancy among rows.)
  Ex:   name              | parent            
        ----------------- | ----------------- 
        Inter-City Travel | Travel  
        Intra-City Travel | Travel
        Travel            |               
        Airfare           | Inter-City Travel
        Rail Train        | Inter-City Travel
        Bicycling         | Intra-City Travel
  '''
  name = models.CharField(max_length=100, unique=False,
          null=False, blank=False) 
  #on_delete for parent attribute handled by category_post_delete_handler
  #Since Django's default behaviour is transactions aren't committed until
  #a request is completed, the post_delete handler will override on_delete
  parent = models.ForeignKey('self', null=True, on_delete=models.SET_NULL) 

  def get_absolute_url(self):
    return reverse('event_recorder:category-detail', kwargs={'pk': self.id})

  def __str__(self):
    return '{}-{}'.format(self.id, self.name)
  
  class Meta:
    ordering = [models.F('parent').asc(nulls_first=True), 'name']#, 'name')

@receiver(models.signals.post_delete, sender=Category,
          dispatch_uid='string id for event category delete')
def category_post_delete_handler(sender, instance, **kwargs):
  ''' Update the parent attribute of all deleted category's children '''
  new_parent = instance.parent
  Category.objects.filter(parent_id=instance.id).update(
    parent=new_parent)


class Relation(models.Model):
  ''' Relation categories for Person model. '''
  name = models.CharField('Relationship Category', max_length = 50, 
          blank=False, null=False)

  def get_absolute_url(self):
    return reverse('event_recorder:relation-detail', kwargs={'pk': self.id})

  def __str__(self):
    return self.name

  class Meta:
    ordering = ('name',)


class GenderChoices(Enum):
  M = 'Male'
  F = 'Female'
  O = 'LGBTQ'

#  @classmethod
#  def 
#    return tuple(x.name, x.value for x in )

class Person(models.Model):
  ''' Person with whom we can share an event experience. '''
  first_name = models.CharField(max_length =50,
                blank=False, null=False)
  last_name = models.CharField(max_length = 50, blank=True)
  relations = models.ManyToManyField(Relation)
  approx_DOB = models.DateTimeField(null = True, blank=True)
  gender = models.CharField(max_length = 1, 
            #x.name is stored in database, x.value is human-readable
            choices = [(x.name, x.value) for x in GenderChoices],
            null=True,
          )

  def get_absolute_url(self):
    return reverse('event_recorder:person-detail', kwargs={'pk': self.id})

  def __str__(self):
    return self.first_name + ' ' + self.last_name
  
  def getAge(self):
    if self.approx_DOB:
      return ((timezone.now() - self.approx_DOB).days)//365
    else:
      return -1

  class Meta:
    ordering = ('first_name', 'last_name')


def oneTimeChunkAgo(n=60):
  ''' Gets datetime object of n-minutes past from now --> default=1hr '''
  return timezone.now() - timezone.timedelta(minutes=n)

class Event(models.Model):
  '''
  Basic event details including start time, end time, description. 
  Also includes two many-to-many relations with Category and Person.
  Finally, includes a notes section in case you want to write about
  the event more in detail (max about 200 words).
  '''
  start_time = models.DateTimeField(default=oneTimeChunkAgo())
  end_time = models.DateTimeField(default=timezone.now, null=True)
  description = models.CharField(max_length = 200, blank=False)
  categories = models.ManyToManyField(Category)
  people = models.ManyToManyField(Person)
  notes = models.CharField(max_length = 1000, default='', blank=True)
  
  def get_absolute_url(self):
    return reverse('event_recorder:event-detail', kwargs={'pk': self.id})

  def __str__(self):
    return '{}: {}'.format(str(self.id), self.description)
  
  def duration(self):
    end = self.end_time if self.end_time else timezone.now()
    return end - self.start_time #datetime.timedelta object
  
  def is_solo_event(self):
    return self.people.get_queryset().count() == 0
  is_solo_event.admin_order_field = 'people'
  is_solo_event.boolean = True
  is_solo_event.short_description = 'Alone?'

  def current_event(self):
    return not self.end_time or self.end_time > timezone.now()

  class Meta:
    ordering = ('-end_time', '-start_time')


class Rating(models.Model):
  '''
  All the ratings (/10) associated with an event. Separate table
  for simplicity and also the fact that people usually just care
  about the overall rating instead of individual scores.
  '''
  event = models.OneToOneField(Event, null=False,
            on_delete = models.CASCADE) 
  enjoyment = models.PositiveSmallIntegerField(
                'Enjoyment Rating', blank=True, null=True) #rating/10
  productivity = models.PositiveSmallIntegerField(
                'Productivity Rating', blank=True, null=True) #rating/10

  def get_absolute_url(self):
    return reverse('event_recorder:rating-detail', kwargs={'pk': self.id})
  
  def __str__(self):
    return '{} ({}) - {} - {}'.format(str(self.event.id), 
      self.event.description, str(self.enjoyment), str(self.productivity))

  def overall_rating(self):
    total_score, denom = 0, 0
    if self.enjoyment:
      total_score += self.enjoyment
      denom += 10
    if self.productivity:
      total_score += self.productivity
      denom += 10
    return total_score/denom*10 if denom > 0 else None
  
  overall_rating.short_description = 'Overall Rating'



#TODO: Define a way to add Photo class : Photo([id], file_path, taken_date)
#TODO: After definining photos, add EventAndPhoto like EventAndCategory
#TODO: EventAndPhoto([ID], event, photo, is_thumbnail (bool) ) 
'''
class Photo
'''

mysite/event_recorder/forms.py
from django import forms
#from django.forms.widgets import CheckboxSelectMultiple
from .models import Category, Event, Person, Relation, Rating

class EventForm(forms.ModelForm):
  class Meta:
    model = Event
    fields = ['start_time', 'end_time', 'description', 
              'categories', 'people']

  def __init__(self, *args, **kwargs):
    
    super(EventForm, self).__init__(*args, **kwargs)
    
    self.fields['categories'].widget = forms.widgets.CheckboxSelectMultiple()
    self.fields['categories'].queryset = Category.objects.all()
    self.fields['categories'].required = False
  
    self.fields['people'].widget = forms.widgets.CheckboxSelectMultiple()
    self.fields['people'].queryset = Person.objects.all()
    self.fields['people'].required = False
  

class CategoryForm(forms.ModelForm):
  class Meta:
    model = Category
    fields = ['name', 'parent']

  def __init__(self, *args, **kwargs):
    
    super(CategoryForm, self).__init__(*args, **kwargs)
    
    self.fields['parent'].required = False
  

class PersonForm(forms.ModelForm):
  class Meta:
    model = Person
    fields = ['first_name', 'last_name', 'relations', 
              'approx_DOB', 'gender']

  def __init__(self, *args, **kwargs):
    
    super(PersonForm, self).__init__(*args, **kwargs)
    
    self.fields['relations'].widget = forms.widgets.CheckboxSelectMultiple()
    self.fields['relations'].queryset = Relation.objects.all()
    self.fields['relations'].required = False
  
    self.fields['gender'].required = False
    self.fields['approx_DOB'].required = False


class RelationForm(forms.ModelForm):
  class Meta:
    model = Relation
    fields = ['name']

#  def __init__(self, *args, **kwargs):
#    
#    super(CategoryForm, self).__init__(*args, **kwargs)
#    
#    self.fields['parent'].required = False

mysite/event_recorder/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic 

from .models import Category, Event, Person, Relation, Rating
from .forms import EventForm, CategoryForm, PersonForm, RelationForm

class IndexView(generic.ListView):
  template_name = 'main/index.html'
  context_object_name = 'main_page'

  def get_queryset(self):
    return None

#Event views
class EventIndexView(generic.ListView):
  model = Event
  context_object_name = 'events_list'
  template_name = 'events/index.html'
  
  def get_queryset(self):
    ''' Excludes any events that haven't started yet. '''
    return Event.objects.filter(start_time__lte=timezone.now())

class EventDetailView(generic.DetailView):
  model = Event
  template_name = 'events/detail.html'
 
class EventCreateView(generic.CreateView):
  model = Event
  form_class = EventForm
  template_name = 'events/create.html'

  def form_valid(self, form):
    print(form.cleaned_data)
    return super().form_valid(form)

class EventUpdateView(generic.UpdateView):
  model = Event
  form_class = EventForm 
  template_name = 'events/update.html'

  def get_object(self, queryset=None):
    obj = Event.objects.get(pk=self.kwargs['pk'])
    return obj

  def form_valid(self, form):
    print(form.cleaned_data)
    return super().form_valid(form)

class EventDeleteView(generic.DeleteView):
  model = Event
  template_name = 'events/delete.html'

  def get_object(self, queryset=None):
    obj = Event.objects.get(pk=self.kwargs['pk'])
    return obj
  
  def get_success_url(self):
    return reverse('event_recorder:events-index')

#Category views
class CategoryIndexView(generic.ListView):
  model = Category
  template_name = 'categories/index.html'
  context_object_name = 'categories_list'

class CategoryDetailView(generic.DetailView):
  model = Category
  template_name = 'categories/detail.html'

class CategoryCreateView(generic.CreateView):
  model = Category
  form_class = CategoryForm
  template_name = 'categories/create.html'

  def form_valid(self, form):
    print(form.cleaned_data)
    return super().form_valid(form)

class CategoryUpdateView(generic.UpdateView):
  model = Category
  form_class = CategoryForm 
  template_name = 'categories/update.html'

  def get_object(self, queryset=None):
    obj = Category.objects.get(pk=self.kwargs['pk'])
    return obj

  def form_valid(self, form):
    print(form.cleaned_data)
    return super().form_valid(form)

class CategoryDeleteView(generic.DeleteView):
  model = Category
  template_name = 'categories/delete.html'

  def get_object(self, queryset=None):
    obj = Category.objects.get(pk=self.kwargs['pk'])
    return obj
  
  def get_success_url(self):
    return reverse('event_recorder:categories-index')

#Person views
class PersonIndexView(generic.ListView):
  model = Person
  template_name = 'people/index.html'
  context_object_name = 'people_list'

class PersonDetailView(generic.DetailView):
  model = Person
  template_name = 'people/detail.html'

class PersonCreateView(generic.CreateView):
  model = Person
  form_class = PersonForm
  template_name = 'people/create.html'

  def form_valid(self, form):
    print(form.cleaned_data)
    return super().form_valid(form)

class PersonUpdateView(generic.UpdateView):
  model = Person
  form_class = PersonForm 
  template_name = 'people/update.html'

  def get_object(self, queryset=None):
    obj = Person.objects.get(pk=self.kwargs['pk'])
    return obj

  def form_valid(self, form):
    print(form.cleaned_data)
    return super().form_valid(form)

class PersonDeleteView(generic.DeleteView):
  model = Person
  template_name = 'people/delete.html'

  def get_object(self, queryset=None):
    obj = Person.objects.get(pk=self.kwargs['pk'])
    return obj
  
  def get_success_url(self):
    return reverse('event_recorder:people-index')

class RelationIndexView(generic.ListView):
  model = Relation
  template_name = 'relations/index.html'
  context_object_name = 'relations_list'

class RelationDetailView(generic.DetailView):
  model = Relation
  template_name = 'relations/detail.html'

class RelationCreateView(generic.CreateView):
  model = Relation
  form_class = RelationForm
  template_name = 'relations/create.html'

class RelationUpdateView(generic.UpdateView):
  model = Relation
  form_class = RelationForm 
  template_name = 'relations/update.html'

  def get_object(self, queryset=None):
    obj = Relation.objects.get(pk=self.kwargs['pk'])
    return obj

class RelationDeleteView(generic.DeleteView):
  model = Relation
  template_name = 'relations/delete.html'

  def get_success_url(self):
    return reverse('event_recorder:relations-index')

#Rating Views
class RatingIndexView(generic.ListView):
  model = Rating
  template_name = 'ratings/index.html'
  context_object_name = 'ratings_list'

class RatingDetailView(generic.DetailView):
  model = Rating
  template_name = 'ratings/detail.html'

'''
class ResultsView(generic.DetailView):
  model = Question
  template_name = 'polls/results.html'

#def index(request):
#  latest_question_list = Question.objects.order_by('-pub_date')[:5]
#  context = {'latest_question_list': latest_question_list}
#  return render(request, 'polls/index.html', context)
#
#def detail(request, question_id):
#  question = get_object_or_404(Question, pk=question_id)
#  return render(request, 'polls/detail.html', {'question': question})
#
#def results(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  try:
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
  except (KeyError, Choice.DoesNotExist):
    # Redisplay the question voting form.
    return render(request, 'polls/detail.html', {
        'question': question,
        'error_message': "You didn't select a choice.",
    })
  else:
    selected_choice.votes += 1
    selected_choice.save()
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('polls:results', \
            args=(question.id,)))
'''

mysite/event_recorder/templates/people/create.html
{% load static %}

<link rel="stylesheet" type="text/css" 
  href="{% static 'events/style.css' %}">

<h1> Create New Person </h1>

<form action='.' method='POST'> {% csrf_token %}
  {{ form.as_p }}
  <p>
    <input type='submit' value='Save'/>
    <a href="{% url 'event_recorder:people-index' %}">Cancel</a> 
  </p>
</form>

mysite/event_recorder/templates/people/delete.html
{% load static %}

<link rel="stylesheet" type="text/css" 
  href="{% static 'events/style.css' %}">


<form action='.' method='POST'> {% csrf_token %}
  <h1>Do you want to delete the person "{{ person.first_name }} {{person.last_name}}"?</h1>
  <p>
    <input type='submit' value='Yes'/> 
    <a href="{% url 'event_recorder:person-detail' person.id %}">Cancel</a> 
  </p>
</form>

mysite/event_recorder/templates/people/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" 
  href="{% static 'events/style.css' %}">

{% if error_message %}
  <p><strong>{{ error_message }}</strong></p>
{% endif %}

<h1> {{ person.first_name }} {{person.last_name}} </h1>

<a href="{% url 'event_recorder:people-index' %}"> All People </a>
<p></p>
<a href="{% url 'event_recorder:person-update' person.id %}"> Update Person </a>
<p></p>
<a href="{% url 'event_recorder:person-delete' person.id %}"> Delete Person </a>
<p></p>

<p><strong> Person id: </strong> {{ person.id }}</p>
<p><strong> First Name: </strong> {{ person.first_name }}</p>
<p><strong> Last Name: </strong> {{ person.last_name }}</p>

<p><strong> Relations: </strong> 
  {% for relation in person.relations.all %}
    <a href= "{% url 'event_recorder:relation-detail' relation.id %}">
      {{relation.name}}
    </a>
    ,  
  {% endfor %}
</p>

<p><strong>Approx Age: </strong> 
  {% if person.approx_DOB %}
    {{ person.getAge }}
  {% endif %}
</p>

<p><strong>Gender: </strong> 
  {% if person.gender %}
    {{ person.gender }}
  {% endif %}
</p>

<h2> Associated Events </h2>
<table id='person_associated_events_table'>
  <tr>
    <th>Description</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th>
      <a href="{% url 'event_recorder:categories-index' %}">
          Categories</a>
    </th>
    <th>People</td>
    <th>Overall Rating</td>
  </tr>
  {% for event in person.event_set.all %}
    <tr>
      <td><a href="{% url 'event_recorder:event-detail' event.id %}">
        {{ event.description }}</a></td>
      <td> {{ event.start_time }}</td>
      {% if event.end_time > now %}
        <td> Present </td>
      {% else %}
        <td> {{ event.end_time }}</td>
      {% endif %}
      <td> 
        {% for category in event.categories.all %}
            <a href="{% url 'event_recorder:category-detail' category.id %}">
                <p> {{ category.name }} </p>
            </a>
        {% endfor %}
      </td>
      <td>
        {% for person in event.people.all %}
          <p> {{ person.first_name }} {{person.last_name }} </p>
        {% endfor %}
      </td>
      <td>
        {% if event.value %}
          <p> {{ event.value.overall_rating }} </p>
        {% endif %}
      </td>

    </tr>
  {% endfor %}
</table>

mysite/event_recorder/templates/people/index.html
{% load static %}

<link rel="stylesheet" type="text/css" 
  href="{% static 'events/style.css' %}">

<h1> People </h1>

<a href="{% url 'event_recorder:person-create' %}"> Add New </a>
<p></p>

{% if people_list %}
  <table id='people_index_table'>
    <tr>
      <th>Name</th>
      <th>  
        <a href="{% url 'event_recorder:relations-index' %}">
          Relations
        </a>
      </th>
      <th>Approx Age</th>
      <th>Gender</th>
    </tr>
    {% for person in people_list %}
      <tr>
        <td>
          <a href=
            "{% url 'event_recorder:person-detail' person.id %}">
            {{ person.first_name }} {{person.last_name}}
          </a>
        </td>
        <td> 
          {% for relation in person.relations.all %}
            <a href=
              "{% url 'event_recorder:relation-detail' relation.id %}">
              {{ relation.name }}
            </a>
          {% endfor %}
        </td>
        <td>
          {% if person.approx_DOB %}
            {{ person.getAge  }}
          {% endif %}
        </td>
        <td>
          {% if person.gender %}
            {{ person.gender }}
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </table>
{% else %}
  <p>No people are defined.</p>
{% endif %}

mysite/event_recorder/templates/people/update.html
{% load static %}

<link rel="stylesheet" type="text/css" 
  href="{% static 'events/style.css' %}">

<h1> Update Person </h1>

<form action='.' method='POST'> {% csrf_token %}
  {{ form.as_p }}
  <p>
    <input type='submit' value='Save'/>
    <a href="{% url 'event_recorder:person-detail' person.id %}">Cancel</a> 
  </p>
</form>